kind: Service
apiVersion: v1
metadata:
  name: hadoop-webhdfs
  labels:
    name: hadoop-webhdfs
spec:
  ports:
    - port: 50070
      targetPort: 50070
      name: hadoop-webhdfs
      
  selector:
    component: hdfs-namenode
  type: LoadBalancer
